config/routes.rb
Rails.application.routes.draw do
  resources :questionnaire_responses

end

app/models/questionnaire_response.rb
class QuestionnaireResponse < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questionnaire_responses_controller.rb
class QuestionnaireResponsesController < ApplicationController
  def new
    @questions = I18n.t(:questions)

  end

  def show
    @questionnaire_response = QuestionnaireResponse.find params[:id]
  end

  def create
    @questionnaire_response = QuestionnaireResponse.new(questionnaire_response_params)
    if @questionnaire_response.save
      redirect_to @questionnaire_response
    else
      render :new
    end

  end

  private

  def questionnaire_response_params
    params.require(:questionnaire_response).permit(data: I18n.t(:questions).map {|k, v| k})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questionnaire_responses_helper.rb
module QuestionnaireResponsesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Formify</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questionnaire_responses/_number_field.html.erb
<%= f.number_field key %>

app/views/questionnaire_responses/_text_field.html.erb
<%= f.text_field key%>

app/views/questionnaire_responses/new.html.erb
<%= form_for 'questionnaire_response[data]', method: :post, url: questionnaire_responses_path do |f| %>
    <% @questions.each do |key, attrs| %>
        <% f.label key, attrs[:question_text] %>
        <%= render attrs[:type], f: f, key: key, attrs: attrs %>

        <%= end %>
    <br>
        <%= f.submit 'Submit' %>
<%= end %>

app/views/questionnaire_responses/show.html.erb
<h1>Questionnaire</h1>
<% @questionnaire_response.data.each do |question, answer| %>
    <%= question.humanize %>: <%= answer %>
    <br>
<% end %>